<%@ page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%>
<%@ taglib uri="/struts-tags" prefix="s"%>
<%@ taglib uri="http://www.joda.org/joda/time/tags" prefix="joda"%>

<%
	response.setHeader("X-Frame-Options", "sameorigin");
	response.setHeader("X-Content-Type-Options", "nosniff");
	response.setHeader("Strict-Transport-Security", "max-age=31536000; includeSubDomains; preload");
%>

<meta http-equiv="Content-Security-Policy" content="default-src 'self'; frame-ancestors 'self'; img-src *;">

<script type="text/javascript" src="js/secondChance.js"></script>
<script type="text/javascript">var page = 3;</script>

<div id="main">
  <div id="topBanner">
    <jsp:include page="../2022/includes/2022-jackpotRaffle_navigation.jsp"></jsp:include>
  </div>
  <div id="mainContentWrap">
    <div id="mainContent">
    
      <h1>
        <s:property value="messages.h1Title"/> <span> 
      </h1>
      
    <p><strong>53ER22 &ndash; JACKPOT RAFFLE PROMOTION.</strong></p>
      
      <ol>
		<li>Beginning October 1, 2022 and ending October 31, 2022 ("Promotion Period"), the Florida Lottery will conduct the Jackpot Raffle Promotion ("Promotion"). Players who purchase a single ticket for any FLORIDA LOTTO&reg;, any JACKPOT TRIPLE PLAY&trade;, any MEGA MILLIONS&reg;, or any POWERBALL&reg; draw game for a $10 or greater purchase price during the Promotion Period will receive a one-time use coupon that may be redeemed for a promotional Raffle ticket for a chance to win a cash prize of $500. Powerball and Mega Millions QUICKTICKETs&trade; are not eligible. Free tickets are not eligible.</li>
		<li><strong>How to Enter.</strong></li>
		<ol type="a">
			<li>A purchase that meets the requirements described in subsection (1), above, will trigger a terminal or vending machine, as applicable, to automatically print a one-time use coupon that may be redeemed for a Raffle ticket. The coupon may be redeemed at any Lottery retailer or Lottery office. The coupon may be redeemed at any time during the Promotion Period but must be redeemed by, and subject to retailer and Lottery office operating hours, 11:59:59 p.m. (ET) on October 31, 2022 (last day of the Promotion Period). At the time of coupon redemption, one Raffle ticket will issue. Should a problem arise concerning the transaction, it is the player's responsibility to seek resolution with the retailer and the Florida Lottery prior to leaving the retail or Lottery office location. <br> The Raffle ticket will contain a unique number that will automatically be entered into the next available Promotion drawing. Players shall keep their Raffle ticket/s, which will be needed for determining if a prize has been won and for redeeming a prize won, if any. Coupons shall not be mailed to the Lottery. Coupons received in the mail will not be processed for entry into a drawing and will not be returned.  </li>
			  <li>The odds of winning depend on the number of entries generated during each drawing entry period. All entries are subject to validation by the Florida Lottery and will be disqualified if eligibility requirements are not met. </li>
		</ol>
		<li><strong>Drawings and Number of Prizes.</strong></li>
		<p>The Florida Lottery will conduct five (5) drawings in the Promotion to select winning numbers. Drawings will be held on the dates listed in the table, below, from the entries generated by 11:59:59 (ET) on the Entry Period end date. The drawings shall be public, held in Tallahassee, Florida, and witnessed by an accountant employed by an independent certified public accounting firm. Entries from any drawing entry period are not carried over into subsequent drawing entry periods. The entry periods, winning numbers drawn/publish dates, and winning Raffle ticket redemption deadline dates are listed in the table, below:</p>
			 <table class="dataTbl" width="500">
                    <thead>
                         <tr>
                              <th width="270" class="txtc">DRAWING ENTRY PERIOD<br><span style="font-size: 13px;">(all dates shown below are inclusive)</span></th>
                              <th width="70" class="txtc">WINNING NUMBERS DRAWN <br>and PUBLISH DATES</th>
                              <th width="50" class="txtc">WINNING RAFFLE TICKET <br>REDEMPTION DEADLINE</th>
                         </tr>
                    </thead>
                    <tbody>
                         <tr class="even">
                              <td class="txtc">October 1, 2022 &dash; October 5, 2022</td>
                              <td class="txtc">October 6, 2022</td>
							 <td class="txtc">April 4, 2023</td>
						</tr>
                         <tr>
                              <td class="txtc">October 6, 2022 &dash; October 12, 2022</td>
                              <td class="txtc">October 13, 2022</td>
							 <td class="txtc">April 11, 2023</td>
                      </tr>
                         <tr class="even">
                              <td class="txtc">October 13, 2022 &dash; October 19, 2022</td>
                              <td class="txtc">October 20, 2022</td>
							 <td class="txtc">April 18, 2023</td>
						</tr>
                         <tr>
                              <td class="txtc">October 20, 2022 &dash; October 26, 2022</td>
                              <td class="txtc">October 27, 2022</td>
							 <td class="txtc">April 25, 2023</td>
                      </tr>
                         <tr class="even">
                              <td class="txtc">October 27, 2022 &dash; October 31, 2022</td>
                              <td class="txtc">November 1, 2022</td>
							 <td class="txtc">April 30, 2023</td>
						</tr>                                            
                    </tbody>
               </table>	
		<li><strong>The prize amounts and number of winners are listed in the table, below:</strong></li>
			 <table class="dataTbl">
                    <thead>
                         <tr>
                              <th width="50" class="txtc">PRIZE<br> AMOUNT</th>
                              <th width="50" class="txtc">NUMBER OF WINNERS <br>PER DRAWING</th>
                              <th width="35" class="txtc">TOTAL NUMBER <br>OF WINNERS</th>
                              <th width="35" class="txtc">TOTAL <br>PRIZE AMOUNT</th>
                         </tr>
                    </thead>
                    <tbody >
                         <tr class="even">
                              <td class="txtc">$500</td>
                              <td class="txtc">100</td>
							 <td class="txtc">500</td>
							 <td class="txtc">$250,000</td>
						</tr>				  
                    </tbody>
               </table>			
		
		<li><strong>How to Claim a Prize.</strong></li>
			<ol type="a">
				<li>Winning numbers in promotional drawings will be posted on the <a href="https://secondchance.floridalottery.com/secondchance">Florida Lottery's website </a> on the ""WINNING NUMBERS DRAWN AND PUBLISH DATES," listed in the table in subsection (3), above, or as soon thereafter as possible. Aside from publication on the Lottery's website, the Lottery will not attempt to further notify any prizewinner. A player may also check his/her Raffle ticket at any Lottery retailer or Lottery office or by scanning the Raffle ticket via "Check My Ticket" on the Florida Lottery's app. </li>
				<li>A player with a winning Raffle ticket may redeem it at any Lottery retailer or Lottery office or may mail it to the Florida Lottery, Attn:  Claims Processing, 250 Marriott Drive, Tallahassee, Florida 32301. Only an original Raffle ticket shall be presented; a copy, photograph, and the like, in any form or other medium will not be accepted. If a player mails in a winning Raffle ticket, the player shall include, in legible writing, his/her name, a mailing address, a telephone number, and an email address, along with the original ticket. Any mailing must be post-marked on or before the applicable WINNING RAFFLE TICKET REDEMPTION DEADLINE date, set forth in the table under subsection (3), above. The risk of mailing remains with the player. The Lottery is not responsible for delays in mailing or lost mail. The deadline for redeeming a winning Raffle ticket is 180 days from the applicable draw date, as set forth in the table under subsection (3), above. </li>
				<li>A player can only win one prize per entry.</li>
				<li>Should any winning Raffle ticket not be redeemed, the prize associated with that winning Raffle ticket will not be awarded.</li>
			</ol>
		<li><strong>Retailer Incentive. </strong></li>
		<p>Retailers issuing a winning Raffle ticket from a coupon redemption will receive a $100.00 bonus. The retailer will receive this bonus whether or not a prizewinner redeems his/her winning Raffle ticket. Retailers will not receive a bonus commission for coupon redemption.</p>
		<li><strong>Taxes.</strong></li>
		<p>All Federal, state, and/or local taxes and/or other costs and fees on all prizes will be the responsibility of the prizewinner.</p>
		<li><strong>Other Restrictions and Provisions.</strong></li>
			<ol type="a">
				<li>A player must be at least 18 years of age.</li>
				<li>All prizes and provisions herein are subject to the provisions of chapter 24, F.S., and rules promulgated thereunder. Copies of the Payment of Prizes rule (53ER22-54, F.A.C.) can be obtained from the Florida Lottery, Office of the General Counsel, 250 Marriott Drive, Tallahassee, Florida 32301.</li>
				<li>Persons prohibited by section 24.116, Fla. Stat., from purchasing a Florida Lottery ticket are not eligible to enter this Promotion.</li>
				<li>By entering the Jackpot Raffle Promotion, a player gives his or her permission for the Florida Lottery to photograph and/or videotape and record the prizewinner with or without prior notification and to use the name, photograph, videotape, and/or recording of the prizewinner for advertising or publicity purposes without additional compensation.</li>
			</ol>		
		<div style="font-size: 11px;">
		<p style="font-style: italic;">Rulemaking Authority 24.105(9), 24.109(1) FS. Law Implemented 24.105(9), 24.107, 24.115(1) FS. History-New 10-1-22. </p>  
   		<p>The official rule for the Jackpot Raffle Promotion can be obtained from the Florida Administrative Code at www.flrules.org on or soon after October 1, 2022. In the event of a conflict between a provision of this rule version and the official rule, the official rule shall govern. </p>
 		</div>  
   </div>
  </div>
</div>
