<%@ page language="java" contentType="text/h&trade;l; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%>
<%@ taglib uri="/struts-tags" prefix="s"%>
<%@ taglib uri="http://www.joda.org/joda/time/tags" prefix="joda"%>

<%
	response.setHeader("X-Frame-Options", "sameorigin");
	response.setHeader("X-Content-Type-Options", "nosniff");
	response.setHeader("Strict-Transport-Security", "max-age=31536000; includeSubDomains; preload");
%>

<meta http-equiv="Content-Security-Policy" content="default-src 'self'; frame-ancestors 'self'; img-src *;">

<script type="text/javascript" src="js/secondChance.js"></script>
<script type="text/javascript">var page = 3;</script>

<div id="main" class="bonusPlayGetaway howtoplay">
	<div id="topBanner">
		<jsp:include page="../2025/includes/2025-Raffle_navigation.jsp"></jsp:include>
	</div>
	
	<div id="mainContentWrap">
		<div id="mainContentWrap">
		<div id="mainContent">
			<h1>RULES</h1>
			<p><strong>53ER25-17 Pick Daily&trade; Promotion (April 7 - May 18, 2025)</strong></p>
			<ol>
				<li>From April 7 through and including May 18, 2025 ("Promotion Period"), the Florida Lottery will conduct the PICK Daily Games Promotion (April 7 - May 18, 2025) ("Promotion").<br />
					<ol type="a">
						<li>Up to, through, and including, the issuance of the 9,999,999th Raffle ticket, or until the end of the Promotion Period, whichever occurs first, one Raffle ticket 
						will be issued to players who purchase a single ticket for any PICK Daily Games draw game that includes the addition of the "Advance Play" feature of seven (7) or 
						more days. PICK games are:  PICK 2&trade;, PICK 3&trade;, PICK 4&trade;, and PICK 5&trade;. 
						</li>
						<li>
							Upon the issuance of the 9,999,999<sup>th</sup> Raffle ticket, Raffle tickets will no longer be issued. 
						</li>
						<li>
							Players holding Raffle tickets will have a chance to win a cash prize of $100.   
						</li>
					</ol>
				</li>		
				<li>
					How to Enter.
					<ol type="a">
						<li>A purchase that meets the requirements described in subsection (1), above, will trigger a terminal or vending machine, as applicable, 
						to automatically print one Raffle ticket. A Winning Alert will sound when a Raffle ticket is generated. A prize alert symbol will print on 
						qualifying draw game tickets. Upon the issuance of the 9,999,999th Raffle ticket, no additional Raffle tickets will be issued. Should a problem 
						arise concerning the transaction, it is a player's responsibility to seek resolution with the retailer and the Florida Lottery prior to leaving 
						the retail or Lottery office location. Each Raffle ticket will contain a unique number that will automatically be entered into the next available 
						Raffle drawing; the next available Raffle draw date will print on a Raffle ticket. Players shall keep their original Raffle ticket/s throughout the 
						Promotion Period, which will be needed for determining if a prize has been won and for redeeming a prize won, if any. 
						</li>
						<li>
							The odds of winning depend on the number of Raffle tickets issued, which constitute entries (one entry per Raffle ticket issued), 
							during each drawing entry period. Upon the occurrence of the issuance of the 9,999,999<sup>th</sup> Raffle ticket, all non-winning Raffle tickets, 
							irrespective of the draw dates shown on Raffle tickets, will be entered into the upcoming drawing, if any, and subsequent Promotion drawings, 
							if any remain. All entries are subject to validation by the Florida Lottery and will be disqualified if eligibility requirements are not met. 
						</li>
					</ol>
						</li>
						<li>
							Drawings and Number of Prizes
						</li>
							<ol type="a">
								<li>
								The Florida Lottery will conduct six (6) drawings in the Promotion to select winning Raffle ticket numbers. Drawings will be held on the dates 
								listed in the table, below, from entries generated by 11:59:59 (ET) on the Drawing Entry Period end date. Drawings will be public, held in Tallahassee, 
								Florida, and witnessed by an accountant employed by an independent certified public accounting firm.
								</li>
								<li>
									Only Raffle tickets issued during a Drawing Entry Period will be entered into the associated drawing. Except that, upon the occurrence of the issuance of the 
									9,999,999<sup>th</sup> Raffle ticket, if such occurs prior to the end of the Promotion Period, all non-winning Raffle tickets issued throughout the Promotion 
									Period (less Raffle tickets previously drawn as winners), irrespective of the drawing dates shown on Raffle tickets, will be entered into an upcoming drawing, 
									if any, and subsequent Promotion drawings, if any remain. 
								</li>
								<li>
									As players are not required to register for a drawing, the only evidence of a winning Raffle ticket is the original Raffle ticket. Players shall retain their 
									original Raffle ticket/s throughout the entire Promotion Period, as it will be required to show proof of a win and be required to redeem a prize won, if any. 
								</li>
								<li>
									Drawing Entry Periods, Winning Raffle Numbers Drawn and Publish Dates, and Winning Raffle Ticket Redemption Deadline dates:
								</li>
								<table class="dataTbl">
									<tr>
										<th>DRAWING ENTRY PERIOD (all dates shown below are inclusive)</th>
										<th>WINNING RAFFLE NUMBERS DRAWN and PUBLISH DATES</th>
										<th>WINNING RAFFLE TICKET REDEMPTION DEADLINE (180 Days from the Applicable Drawing Date)</th>
									</tr>
									<tr>
										<td>April 7 - April 13, 2025</td>
										<td>April 14, 2025</td>
										<td>October 11, 2025</td>
									</tr>
									<tr>
										<td>April 14 - April 20, 2025</td>
										<td>April 21, 2025</td>
										<td>October 18, 2025</td>
									</tr>
									<tr>
										<td>April 21 - April 27, 2025</td>
										<td>April 28, 2025</td>
										<td>October 25, 2025</td>
									</tr>
									<tr>
										<td>April 28 - May 4, 2025</td>
										<td>May 5, 2025</td>
										<td>November 1, 2025</td>
									</tr>
									<tr>
										<td>May 5 - May 11, 2025</td>
										<td>Mat 12, 2025</td>
										<td>November 8, 2025</td>
									</tr>
									<tr>
										<td>May 12 - May 18,, 2025</td>
										<td>May 19, 2025</td>
										<td>November 15, 2025</td>
									</tr>
								</table>
							</ol>
						<li>
							Prize Amounts and number of winners:
							<table class="dataTbl">
								<tr>
									<th>PRIZE AMOUNT</th>
									<th>NUMBER OF WINNERS PER DRAWING</th>
									<th>TOTAL NUMBER OF WINNERS</th>
									<th>TOTAL PRIZE AMOUNT</th>
								</tr>
								<tr>
									<td>$100</td>
									<td>100</td>
									<td>600</td>
									<td>$60,000</td>
								</tr>
							</table>
						</li>
						<li>
							How to Claim a Prize.
							<ol type="a">
								<li>
									Winning Raffle numbers in promotional drawings will be posted on the Florida Lottery's website at <a href="https://floridalottery.com">www.floridalottery.com</a> 
									(navigate to the WINNER's tab listed on the PICK Daily Games Promotion landing page) on the "WINNING RAFFLE NUMBERS DRAWN 
									and PUBLISH DATES," listed in the table in subsection (3), above, or as soon thereafter as possible. Aside from publication on the Lottery's 
									website, the Lottery will not attempt to further notify any winner. A player may also check his/her Raffle ticket at any Lottery retailer or 
									Lottery office or by scanning the Raffle ticket via "Check My Ticket" on the Florida Lottery's app.
								</li>
								<li>
									A player with a winning Raffle ticket may redeem it at any Lottery retailer, providing a retailer has sufficient cash on hand or 
									otherwise has the ability to issue prize payment, or Lottery office or may mail it to the Florida Lottery, Attn:  Claims Processing, 
									250 Marriott Drive, Tallahassee, Florida 32301. Only an original Raffle ticket shall be honored for prize redemption; a copy, photograph, 
									and the like, in any form or in any medium will not be accepted. If a player mails in a winning Raffle ticket, the player shall include, 
									in legible writing, his/her name, mailing address, telephone number, and an email address, along with the original Raffle ticket. 
									Any mailing must be post-marked on or before the applicable WINNING RAFFLE TICKET REDEMPTION DEADLINE date, set forth in the table under subsection (3), 
									above. The risk of mailing remains with the player. The Lottery is not responsible for delays in mailing or lost/stolen mail. Raffle tickets redeemed in 
									person must be redeemed by the applicable WINNING RAFFLE TICKET REDEMPTION DEADLINE date by 11:59:59 p.m. (ET), set forth in the table under subsection (3), 
									above, subject to retailer and Lottery office operating hours.
								</li>
								<li>
									A player can only win one prize per Raffle ticket.
								</li>
								<li>
									Should any winning Raffle ticket not be redeemed, the prize associated with that winning Raffle ticket will not be awarded, and the player will not otherwise be compensated. 
									In the event that 9,999,999 Raffle tickets are not issued by the end of the Promotion Period, any remaining tickets will not otherwise be issued.
								</li>
							</ol>
							<li>
								Taxes. All federal, state, and/or local taxes and/or other costs and fees on all prizes will be the responsibility of winners.
							</li>
							<li>
								Other Restrictions and Provisions.
								<ol type="a">
									<li>Players must be at least 18 years of age.</li>
									<li>All prizes and provisions herein are subject to the provisions of chapter 24, Fla. Stat., and rules promulgated thereunder. Copies of the Payment of Prizes rule (Emergency Rule 53ER23-20) can be obtained from the Florida Lottery, Office of the General Counsel, 250 Marriott Drive, Tallahassee, Florida 32301 or at flrules.org.</li>
									<li>Persons prohibited by section 24.116, Fla. Stat., from purchasing a Florida Lottery ticket are not eligible to enter this Promotion.</li>
									<li>By entering the PICK Daily Games Promotion, a player gives his/her permission for the Florida Lottery to photograph and/or videotape and record the winner with or without prior notification and to use the name, photograph, videotape, and/or recording of the winner for advertising or publicity purposes without additional compensation.</li>
									<li>If there is a conflict between a provision set forth in this Rule and any promotion materials, including, but not limited to, point of sale, television, radio, and print advertising, and other promotional media/materials, the terms of this Rule shall prevail.</li>
								</ol>
							</li>
										
					</ol>
				</li>	
				

			</ol>
			
		<i>Rulemaking Authority 24.105(9), 24.109(1) FS. Law Implemented 24.105(9), 24.107, 24.115(1) FS. History-New 4-7-2025.</i>
		<br><br>
			The official rule for PICK Daily Games Promotion (April 7 - May 18, 2025) can be obtained from the Florida Administrative Code at www.flrules.org on or soon after April 7, 2025. In the event of a conflict between a provision of this rule version and the official rule, the official rule shall govern.
		</div>
	</div>
	</div>
</div>